version: "3.1"
services:

  db_users:
    container_name: db-users
    networks:
      - backend
    image: mongo:latest
    restart: always
    volumes:
      - /Users/john/Documents/Volumes/Users/mongo:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none

  api_users:
    container_name: api-users
    networks:
      - backend
    build:
      context: ./users/src/deployment
      dockerfile: Dockerfile
    depends_on:
      - db_users
    volumes:
      - ./users:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - DATABASE_PUBLIC_URL=db
      - PORT=9000
      - MONGO_DEVELOPMENT=mongodb://db_users:27017/users
    command: sh -c "npm install && npm run watch"

  db_surveys:
    container_name: db-surveys
    networks:
      - backend
    image: mongo:latest
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - /Users/john/Documents/Volumes/Surveys/mongo:/data/db

  api_surveys:
    container_name: api_surveys
    networks:
      - backend
    build:
      context: ./survey/src/deployment
      dockerfile: Dockerfile
    depends_on:
      - db_surveys
    volumes:
      - ./survey:/app
      - /app/node_modules
    ports:
      - "9001:9001"
    environment:
      - NODE_ENV=development
      - DATABASE_PUBLIC_URL=db
      - PORT=9001
      - MONGO_DEVELOPMENT=mongodb://db_surveys:27018/surveys
    command: sh -c "npm install && npm run watch"

  zookeeper:
    image: "bitnami/zookeeper:3.7.0-debian-10-r86"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:2.8.0-debian-10-r54"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  data01:
    driver: local

networks:
  backend:
    driver: bridge
